# permissions for end users to view bbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bb-viewer-role
rules:
- apiGroups:
  - bar.my.domain
  resources:
  - bbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bar.my.domain
  resources:
  - bbs/status
  verbs:
  - get
